### PR TITLE
update home interface and make responsive website

### PR DESCRIPTION
**Pull request by Dreamerchase**
**mimize2
mimize1
mimize3
mimize4
update footer
update navbar in home screen
update container 
between space in two container minimize**

### CODE REVIEW

**Comment by jinsel** [comment]
Can you give little margin between the cards during responsive, as now they are touching with each other.

**Comment by Dreamerchase** [comment]
yes sir

**Comment by Dreamerchase** [comment]
**update interface see like that
mimize5**

**Comment by jinsel** [comment]
Hey can you update the other page too

**Pull request merged**
